package com.example.surveyapi.global.event;

public enum EventCode {
	SURVEY_CREATED,
	SURVEY_UPDATED,
	SURVEY_DELETED,
	SURVEY_ACTIVATED,
	USER_WITHDRAW,
	PROJECT_STATE_CHANGED,
	PROJECT_DELETED,
	PROJECT_ADD_MANAGER,
	PROJECT_ADD_MEMBER,
	PARTICIPATION_CREATED,
	PARTICIPATION_UPDATED
}
