package com.example.surveyapi.global.enums;

public enum EventCode {
	SURVEY_CREATED,
	SURVEY_UPDATED,
	SURVEY_DELETED,
	SURVEY_ACTIVATED,
	USER_WITHDRAW,
	PARTICIPATION_CREATED,
	PARTICIPATION_UPDATED
}
