# 공통 설정
spring:
  # 기본 프로필을 dev로 설정
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# =======================================================
# == Actuator 공통 설정 추가
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# =======================================================

---
# 개발(dev) 프로필 - 로컬 PostgreSQL DB 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_SCHEME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

logging:
  level:
    org.springframework.security: DEBUG

# JWT Secret Key
jwt:
  secret:
    key: ${SECRET_KEY}

oauth:
  kakao:
    client-id: ${CLIENT_ID}
    redirect-uri: ${REDIRECT_URL}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

---
# 운영(prod) 프로필 - PostgreSQL (EC2 등 외부 서버) 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# =======================================================
# == 운영(prod) 환경을 위한 Actuator 보안 설정
management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus"
# =======================================================