
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
          batch_versioned_data: true
          order_inserts: true
          order_updates: true
        batch_fetch_style: DYNAMIC
        default_batch_fetch_size: 100
  cache:
    cache-names:
      - projectMemberCache
      - projectStateCache
    caffeine:
      spec: >
        initialCapacity=200,
        maximumSize=1000,
        expireAfterWrite=10m,
        expireAfterAccess=5m,
        recordStats
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  elasticsearch:
    uris: ${ELASTIC_URIS}
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      authentication-database: ${MONGODB_AUTHDB}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADDRESS:}
    password: ${MAIL_PASSWORD:}
    enabled: ${SPRING_MAIL_ENABLED:false}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
firebase:
  enabled: ${FIREBASE_ENABLED:true}
  project-id: ${FIREBASE_PROJECT_ID:survey-f5a93}
  private-key-id: ${FIREBASE_PRIVATE_KEY_ID}
  private-key: ${FIREBASE_PRIVATE_KEY}
  client-email: ${FIREBASE_CLIENT_EMAIL:firebase-adminsdk-fbsvc@survey-f5a93.iam.gserviceaccount.com}
  client-id: ${FIREBASE_CLIENT_ID:100191250643521230154}

server:
  tomcat:
    threads:
      max: 50
      min-spare: 20

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
  health:
    elasticsearch:
      enabled: ${MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED:false}
    mail:
      enabled: ${MANAGEMENT_HEALTH_MAIL_ENABLED:false}

jwt:
  secret:
    key: ${SECRET_KEY}
  statistic:
    token: ${STATISTIC_TOKEN:}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URL}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_SECRET}
    redirect-uri: ${NAVER_REDIRECT_URL}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URL}
